development:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
production:
  server: "http://localhost/faye/faye"
  secret_token: "8b48d29e5f6f770d177c034062e9ad500dd987189ebe266d50f81fc0e0e3fc5d"
  signature_expiration: 3600 # one hour
